set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_C_COMPILER  sdcc)
set(SDCCLIB_EXECUTABLE sdar)
set(CMAKE_AR_OPTIONS "-rc")
set(CMAKE_FIND_ROOT_PATH /usr/share/sdcc)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS "-mstm8 --std-c11 -D${MCU} -DSDCC")
if("${BUILD_TYPE}" STREQUAL "debug")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --all-callee-saves --debug --verbose --stack-auto --fverbose-asm --float-reent --no-peep")
endif()
